services:
  - type: web
    name: flask-chatbot4
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.10