services:
  - type: web
    name: flask-chatbot4
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10
